version: "3.8"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    networks:
      - intranet

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: recode
      MYSQL_DATABASE: recode
      MYSQL_PASSWORD: recode
      MYSQL_ROOT_PASSWORD: recode
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - intranet

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    ports:
      - 80:80
    networks:
      - intranet

networks:
  intranet:

volumes:
  portainer_data:
  mysql_data:
